# Generated by Django 5.0.6 on 2024-06-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment_method',
            table='Payment_method',
        ),
        migrations.AlterModelTable(
            name='tax',
            table='Tax',
        ),
        migrations.AlterModelTable(
            name='technology',
            table='Technology',
        ),
        migrations.AlterModelTable(
            name='technology_option',
            table='Technology_option',
        ),
    ]
