# Generated by Django 5.0.6 on 2024-06-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_payment_method_table_alter_tax_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='technology',
            table='technology',
        ),
    ]
