# Generated by Django 5.0.6 on 2024-06-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_team_alter_client_user_id_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
