# Generated by Django 5.0.6 on 2024-06-14 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_item',
            fields=[
                ('invoice_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_price', models.IntegerField()),
                ('tax_id', models.IntegerField()),
                ('tax_amount', models.IntegerField()),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.invoice')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.project')),
            ],
            options={
                'db_table': 'invoice_item',
            },
        ),
    ]
