# Generated by Django 5.0.6 on 2024-06-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_technology_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment_method',
            table='payment_method',
        ),
        migrations.AlterModelTable(
            name='tax',
            table='tax',
        ),
        migrations.AlterModelTable(
            name='technology_option',
            table='technology_option',
        ),
    ]
