# Generated by Django 5.0.6 on 2024-06-14 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_invoice_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('payment_date', models.DateField()),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.invoice')),
                ('method_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.payment_method')),
            ],
        ),
    ]
