# Generated by Django 5.0.6 on 2024-06-14 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_invoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='tax_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.tax'),
        ),
    ]
