# Generated by Django 5.0.6 on 2024-06-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_payment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
    ]
