# Generated by Django 5.0.6 on 2024-06-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_alter_invoice_item_tax_id'),
        ('Client', '0005_payment'),
    ]

    operations = [
    ]
