# Generated by Django 5.0.6 on 2024-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_user', '0002_alter_coreuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
