# Generated by Django 5.0.6 on 2024-06-11 08:57

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_user', '0003_alter_coreuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
