# Generated by Django 5.0.6 on 2024-06-11 09:02

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_user', '0004_alter_coreuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
