# Generated by Django 5.0.6 on 2024-06-12 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_user', '0006_city_country_role_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=5, max_digits=5)),
                ('id_proof', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.BigIntegerField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_user.city')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_user.country')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_user.role')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_user.state')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
